### ISSUE TITLE
Detect 'coordinate  location' property for Wikidata pages

### ISSUE THREAD

**Issue by ghost** [FlominatorTM/wikipedia_nearest_photographers#12]
(https://wikidata.org/wiki/Property:P625)

I tried the tool out on https://wikidata.org/wiki/Q111722260 without luck, I think it's looking for the {{coords}} template and not seeing it?

**Comment by FlominatorTM** [comment]
What exactly did you try and what result did you expect?

**Comment by ghost** [comment]
Oops, didn't see you had replied until just now. I expected to be able to supply a Wikidata item and have the tool suggest Wikimedians close to the coords for that item that could take a photo of it. Here's what I tried: 
![image](https://user-images.githubusercontent.com/634501/167158233-8a4c4114-7565-425a-8c23-09f58f49165c.png)
and the result: 
![image](https://user-images.githubusercontent.com/634501/167158488-cbfca437-476f-4418-ab11-e5ea768183b4.png)
When I saw that it added in an 'en' prefix anyway, I tried 
![image](https://user-images.githubusercontent.com/634501/167158584-12367234-1db9-4af0-b0e7-1df3749cbe0a.png)
with the same results.

**Comment by FlominatorTM** [comment]
You need to enter www as language in order to make it work. Sorry for the late reply.

**Comment by ghost** [comment]
Ah, I should have suspected. Maybe change the suggestion of "en, commons, …" to "en, commons, www, …"?
